name: Workflow GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Altere a versão do Node.js, se necessário

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm uninstall bcrypt # Remova a instalação do bcrypt
          npm install
 
      - name: Install bcryptjs and run tests
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SECRET_JWT: '176b58d9ce75355402b1e146cdbfa90f'
        run: |
          npm install bcryptjs
          npm test
          
